// Code generated by protoc-gen-go. DO NOT EDIT.
// source: number_msg.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Answer struct {
	Value                int32    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Answer) Reset()         { *m = Answer{} }
func (m *Answer) String() string { return proto.CompactTextString(m) }
func (*Answer) ProtoMessage()    {}
func (*Answer) Descriptor() ([]byte, []int) {
	return fileDescriptor_798c4d509ab15149, []int{0}
}

func (m *Answer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Answer.Unmarshal(m, b)
}
func (m *Answer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Answer.Marshal(b, m, deterministic)
}
func (m *Answer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Answer.Merge(m, src)
}
func (m *Answer) XXX_Size() int {
	return xxx_messageInfo_Answer.Size(m)
}
func (m *Answer) XXX_DiscardUnknown() {
	xxx_messageInfo_Answer.DiscardUnknown(m)
}

var xxx_messageInfo_Answer proto.InternalMessageInfo

func (m *Answer) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type OperationParameters struct {
	A                    int32    `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B                    int32    `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OperationParameters) Reset()         { *m = OperationParameters{} }
func (m *OperationParameters) String() string { return proto.CompactTextString(m) }
func (*OperationParameters) ProtoMessage()    {}
func (*OperationParameters) Descriptor() ([]byte, []int) {
	return fileDescriptor_798c4d509ab15149, []int{1}
}

func (m *OperationParameters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperationParameters.Unmarshal(m, b)
}
func (m *OperationParameters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperationParameters.Marshal(b, m, deterministic)
}
func (m *OperationParameters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperationParameters.Merge(m, src)
}
func (m *OperationParameters) XXX_Size() int {
	return xxx_messageInfo_OperationParameters.Size(m)
}
func (m *OperationParameters) XXX_DiscardUnknown() {
	xxx_messageInfo_OperationParameters.DiscardUnknown(m)
}

var xxx_messageInfo_OperationParameters proto.InternalMessageInfo

func (m *OperationParameters) GetA() int32 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *OperationParameters) GetB() int32 {
	if m != nil {
		return m.B
	}
	return 0
}

func init() {
	proto.RegisterType((*Answer)(nil), "pb.Answer")
	proto.RegisterType((*OperationParameters)(nil), "pb.OperationParameters")
}

func init() {
	proto.RegisterFile("number_msg.proto", fileDescriptor_798c4d509ab15149)
}

var fileDescriptor_798c4d509ab15149 = []byte{
	// 126 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xc8, 0x2b, 0xcd, 0x4d,
	0x4a, 0x2d, 0x8a, 0xcf, 0x2d, 0x4e, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48,
	0x52, 0x92, 0xe3, 0x62, 0x73, 0xcc, 0x2b, 0x2e, 0x4f, 0x2d, 0x12, 0x12, 0xe1, 0x62, 0x2d, 0x4b,
	0xcc, 0x29, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x82, 0x70, 0x94, 0x0c, 0xb9, 0x84,
	0xfd, 0x0b, 0x52, 0x8b, 0x12, 0x4b, 0x32, 0xf3, 0xf3, 0x02, 0x12, 0x8b, 0x12, 0x73, 0x53, 0x4b,
	0x52, 0x8b, 0x8a, 0x85, 0x78, 0xb8, 0x18, 0x13, 0xa1, 0x0a, 0x19, 0x13, 0x41, 0xbc, 0x24, 0x09,
	0x26, 0x08, 0x2f, 0xc9, 0x89, 0x2d, 0x8a, 0x45, 0x4f, 0xbf, 0x20, 0x29, 0x89, 0x0d, 0x6c, 0x8b,
	0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x97, 0x7c, 0x2d, 0xbd, 0x79, 0x00, 0x00, 0x00,
}
